apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.serviceConfigMap.name }}
  labels:
    app: {{ .Values.configMap.serviceConfigMap.labels.app }}
data:
  # Database configuration
  POSTGRES_DB_MOVIE: {{ .Values.configMap.serviceConfigMap.data.postgresDbMovie | quote }}
  POSTGRES_DB_CAST: {{ .Values.configMap.serviceConfigMap.data.postgresDbCast | quote }}
  POSTGRES_USER_MOVIE: {{ .Values.configMap.serviceConfigMap.data.postgresUserMovie | quote }}
  POSTGRES_USER_CAST: {{ .Values.configMap.serviceConfigMap.data.postgresUserCast | quote }}
  
  # Service URLs and endpoints
  CAST_SERVICE_HOST_URL: {{ .Values.configMap.serviceConfigMap.data.castServiceHostUrl | quote }}
  
  # Application configuration
  APP_HOST: {{ .Values.configMap.serviceConfigMap.data.appHost | quote }}
  APP_PORT: {{ .Values.configMap.serviceConfigMap.data.appPort | quote }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.nginxConfig.name }}
data:
  nginx.conf: {{ .Values.configMap.nginxConfig.data.nginxConf | quote }}