apiVersion: v1
kind: ConfigMap
metadata:
  name: service-configmap
  labels:
    app: service-configmap
data:
  # Database configuration
  POSTGRES_DB_MOVIE: "movie_db_dev"
  POSTGRES_DB_CAST: "cast_db_dev"
  POSTGRES_USER_MOVIE: "movie_db_username"
  POSTGRES_USER_CAST: "cast_db_username"
  
  # Service URLs and endpoints
  CAST_SERVICE_HOST_URL: "http://cast-service:8000/api/v1/casts/"
  
  # Application configuration
  APP_HOST: "0.0.0.0"
  APP_PORT: "8000"
  
  # Database hosts
  # MOVIE_DB_HOST: "movie-db-service"
  # CAST_DB_HOST: "cast-db-service"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }
    
    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;
        
        upstream movie-service {
            server movie-service:8000;
        }
        
        upstream cast-service {
            server cast-service:8000;
        }
        
        server {
            listen 80;
            server_name localhost;
            
            location /api/v1/movies {
                proxy_pass http://movie-service/api/v1/movies;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
            
            location /api/v1/casts {
                proxy_pass http://cast-service/api/v1/casts;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
        }
    }