apiVersion: v1
kind: ConfigMap
metadata:
  name: movie-configmap
  labels:
    app: movie-configmap
data:
  # Database configuration
  POSTGRES_DB_MOVIE: "movie_db_dev"
  POSTGRES_DB_CAST: "cast_db_dev"
  POSTGRES_USER_MOVIE: "movie_db_username"
  POSTGRES_USER_CAST: "cast_db_username"
  
  # Service URLs and endpoints
  CAST_SERVICE_HOST_URL: "http://cast-service:8000/api/v1/casts/"
  
  # Application configuration
  APP_HOST: "0.0.0.0"
  APP_PORT: "8000"
  
  # Database hosts
  # MOVIE_DB_HOST: "movie-db-service"
  # CAST_DB_HOST: "cast-db-service"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    server {
      listen 8080;

      location /api/v1/movies {
        proxy_pass http://movie_service:8000/api/v1/movies;
      }

      location /api/v1/casts {
        proxy_pass http://cast_service:8000/api/v1/casts;
      }

    }