apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-deployment
  labels:
    app: movie-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-deployment
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
      labels:
        app: movie-deployment
    spec:
      containers:
        - name: movie-container
          image: "nils06/movie-service:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8000
          env:
            - name: DATABASE_URI
              valueFrom:
                secretKeyRef:
                  name: movie-secrets-string
                  key: DATABASE_URI_MOVIE
            - name: CAST_SERVICE_HOST_URL
              valueFrom:
                configMapKeyRef:
                  name: service-configmap
                  key: CAST_SERVICE_HOST_URL
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cast-deployment
  labels:
    app: cast-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cast-deployment
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
      labels:
        app: cast-deployment
    spec:
      containers:
        - name: cast-container
          image: "nils06/cast-service:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8000
          env:
            - name: DATABASE_URI
              valueFrom:
                secretKeyRef:
                  name: movie-secrets-string
                  key: DATABASE_URI_CAST
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-deployment
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
      labels:
        app: nginx-deployment
    spec:
      containers:
        - name: nginx-container
          image: "nginx:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - mountPath: /etc/nginx
              name: nginx-conf
              subPath: nginx.conf
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf