apiVersion: v1
kind: Secret
metadata:
  name: movie-secrets-string
  labels:
    app: movie-secrets
type: Opaque
stringData:
  # Database passwords (plain text - will be automatically base64 encoded)
  POSTGRES_PASSWORD_MOVIE: "movie_db_password"
  POSTGRES_PASSWORD_CAST: "cast_db_password"
  
  # Database URIs (plain text - will be automatically base64 encoded)
  DATABASE_URI_MOVIE: "postgresql://movie_db_username:movie_db_password@movie-db-service:5432/movie_db_dev"
  DATABASE_URI_CAST: "postgresql://cast_db_username:cast_db_password@cast-db-service:5432/cast_db_dev"
