apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.movieSecrets.name }}
  labels:
    app: {{ .Values.secrets.movieSecrets.labels.app }}
type: {{ .Values.secrets.movieSecrets.type }}
stringData:
  # Database passwords (plain text - will be automatically base64 encoded)
  POSTGRES_PASSWORD_MOVIE: {{ .Values.secrets.movieSecrets.stringData.postgresPasswordMovie | quote }}
  POSTGRES_PASSWORD_CAST: {{ .Values.secrets.movieSecrets.stringData.postgresPasswordCast | quote }}
  
  # Database URIs (plain text - will be automatically base64 encoded)
  DATABASE_URI_MOVIE: {{ .Values.secrets.movieSecrets.stringData.databaseUriMovie | quote }}
  DATABASE_URI_CAST: {{ .Values.secrets.movieSecrets.stringData.databaseUriCast | quote }}
