apiVersion: v1
kind: Service
metadata:
  name: movie-service
  labels:
    app: movie-service
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: movie-deployment
---
apiVersion: v1
kind: Service
metadata:
  name: cast-service
  labels:
    app: cast-service
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: cast-deployment
---
apiVersion: v1
kind: Service
metadata:
  name: movie-db-service
  labels:
    app: movie-db
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    app: movie-db
---
apiVersion: v1
kind: Service
metadata:
  name: cast-db-service
  labels:
    app: cast-db
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    app: cast-db
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx-deployment
spec:
  type: NodePort
  selector:
    app: nginx-deployment
  ports:
    - name: http
      port: 8080      
      targetPort: 8080
      nodePort: 30080 