# Global configuration
global:
  imageRegistry: ""
  imagePullSecrets: []

# Movie Service Configuration
movieService:
  name: movie-service
  deployment:
    name: movie-deployment
    replicas: 1
    labels:
      app: movie-deployment
    image:
      repository: nils06/movie-service
      tag: latest
      pullPolicy: Always
    container:
      name: movie-container
      port: 8000
      env:
        databaseUriSecret:
          name: movie-secrets-string
          key: DATABASE_URI_MOVIE
        castServiceUrlConfigMap:
          name: service-configmap
          key: CAST_SERVICE_HOST_URL
  service:
    name: movie-service
    type: ClusterIP
    port: 8000
    targetPort: 8000
    protocol: TCP
    labels:
      app: movie-service

# Cast Service Configuration
castService:
  name: cast-service
  deployment:
    name: cast-deployment
    replicas: 1
    labels:
      app: cast-deployment
    image:
      repository: nils06/cast-service
      tag: latest
      pullPolicy: Always
    container:
      name: cast-container
      port: 8000
      env:
        databaseUriSecret:
          name: movie-secrets-string
          key: DATABASE_URI_CAST
  service:
    name: cast-service
    type: ClusterIP
    port: 8000
    targetPort: 8000
    protocol: TCP
    labels:
      app: cast-service

# Movie Database Configuration
movieDb:
  name: movie-db
  statefulset:
    name: movie-db-statefulset
    replicas: 1
    labels:
      app: movie-db
    image:
      repository: postgres
      tag: 12.1-alpine
      pullPolicy: IfNotPresent
    container:
      name: movie-db-container
      port: 5432
      env:
        postgresUser:
          configMapName: service-configmap
          key: POSTGRES_USER_MOVIE
        postgresPassword:
          secretName: movie-secrets-string
          key: POSTGRES_PASSWORD_MOVIE
        postgresDb:
          configMapName: service-configmap
          key: POSTGRES_DB_MOVIE
      volumeMount:
        name: postgres-data-movie
        mountPath: /var/lib/postgresql/data
    storage:
      size: 1Gi
      accessModes:
        - ReadWriteOnce
  service:
    name: movie-db-service
    type: ClusterIP
    port: 5432
    targetPort: 5432
    protocol: TCP
    labels:
      app: movie-db

# Cast Database Configuration
castDb:
  name: cast-db
  statefulset:
    name: cast-db-statefulset
    replicas: 1
    labels:
      app: cast-db
    image:
      repository: postgres
      tag: 12.1-alpine
      pullPolicy: IfNotPresent
    container:
      name: cast-db-container
      port: 5432
      env:
        postgresUser:
          configMapName: service-configmap
          key: POSTGRES_USER_CAST
        postgresPassword:
          secretName: movie-secrets-string
          key: POSTGRES_PASSWORD_CAST
        postgresDb:
          configMapName: service-configmap
          key: POSTGRES_DB_CAST
      volumeMount:
        name: postgres-data-cast
        mountPath: /var/lib/postgresql/data
    storage:
      size: 1Gi
      accessModes:
        - ReadWriteOnce
  service:
    name: cast-db-service
    type: ClusterIP
    port: 5432
    targetPort: 5432
    protocol: TCP
    labels:
      app: cast-db

# Nginx Configuration
nginx:
  name: nginx-deployment
  deployment:
    name: nginx-deployment
    replicas: 1
    labels:
      app: nginx-deployment
    image:
      repository: nginx
      tag: latest
      pullPolicy: IfNotPresent
    container:
      name: nginx-deployment
      port: 80
      volumeMount:
        name: nginx-config
        mountPath: /etc/nginx/nginx.conf
        subPath: nginx.conf
      volume:
        name: nginx-config
        configMapName: nginx-config
  service:
    name: nginx-service
    type: NodePort
    port: 80
    targetPort: 80
    nodePort: 30050
    labels:
      app: nginx-deployment

# ConfigMap Configuration
configMap:
  serviceConfigMap:
    name: service-configmap
    labels:
      app: service-configmap
    data:
      # Database configuration
      postgresDbMovie: movie_db_dev
      postgresDbCast: cast_db_dev
      postgresUserMovie: movie_db_username
      postgresUserCast: cast_db_username
      
      # Service URLs and endpoints
      castServiceHostUrl: http://cast-service:8000/api/v1/casts/
      
      # Application configuration
      appHost: 0.0.0.0
      appPort: "8000"
  
  nginxConfig:
    name: nginx-config
    data:
      nginxConf: |
        events {
            worker_connections 1024;
        }
        
        http {
            include       /etc/nginx/mime.types;
            default_type  application/octet-stream;
            
            upstream movie-service {
                server movie-service:8000;
            }
            
            upstream cast-service {
                server cast-service:8000;
            }
            
            server {
                listen 80;
                server_name localhost;
                
                location /api/v1/movies {
                    proxy_pass http://movie-service/api/v1/movies;
                    proxy_set_header Host $host;
                    proxy_set_header X-Real-IP $remote_addr;
                    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                    proxy_set_header X-Forwarded-Proto $scheme;
                }
                
                location /api/v1/casts {
                    proxy_pass http://cast-service/api/v1/casts;
                    proxy_set_header Host $host;
                    proxy_set_header X-Real-IP $remote_addr;
                    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                    proxy_set_header X-Forwarded-Proto $scheme;
                }
            }
        }

# Secrets Configuration
secrets:
  movieSecrets:
    name: movie-secrets-string
    labels:
      app: movie-secrets
    type: Opaque
    stringData:
      # Database passwords
      postgresPasswordMovie: movie_db_password
      postgresPasswordCast: cast_db_password
      
      # Database URIs
      databaseUriMovie: postgresql://movie_db_username:movie_db_password@movie-db-service:5432/movie_db_dev
      databaseUriCast: postgresql://cast_db_username:cast_db_password@cast-db-service:5432/cast_db_dev